---
driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 2048

provisioner:
  name: chef_zero
  require_chef_omnibus: 11.12.4
  data_bags_path: ../../data_bags
  environments_path: ../../environments
  encrypted_data_bag_secret_key_path: ~/.chef/secrets/your-data-bag-secret
  client_rb:
    environment: dev

platforms:
  - name: ubuntu-12.04
    driver_config:
      box: opscode-ubuntu-12.04
      network:
        - ['private_network', { ip: '33.33.33.133' }]

suites:
  - name: default
    run_list:
      - recipe[prose::default]
