name             'prose'
maintainer       'Christian Nunciato'
maintainer_email 'cnunciato@gmail.com'
license          'all_rights'
description      'Installs/Configures Prose and Prose Gatekeeper'
long_description 'Installs/Configures Prose and Prose Gatekeeper'
version          '0.1.0'

depends 'apt'
depends 'build-essential'
depends 'nodejs'
depends 'omnibus'
depends 'nginx'
depends 'runit'